# Generated by Django 6.1.1 on 2026-09-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0063_alter_organization_sourcing_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpart',
            name='alternates',
            field=models.ManyToManyField(blank=True, to='bom.partrevision'),
        ),
    ]
