# Generated by Django 6.1.1 on 2026-09-09 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0064_subpart_alternates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartClassWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.BOM_ORGANIZATION_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partclass',
            name='workflow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bom.partclassworkflow'),
        ),
        migrations.CreateModel(
            name='PartClassWorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_final_state', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.BOM_ORGANIZATION_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='partclassworkflow',
            name='initial_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bom.partclassworkflowstate'),
        ),
        migrations.CreateModel(
            name='PartClassWorkflowStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_in_workflow', models.CharField(default='forward', max_length=15)),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_state', to='bom.partclassworkflowstate')),
                ('target_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_state', to='bom.partclassworkflowstate')),
                ('workflow', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bom.partclassworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='PartClassWorkflowCompletedTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notifying_next_users', models.BooleanField(default=True, verbose_name='Notifying next users')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bom.part')),
                ('transition', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bom.partclassworkflowstatetransition')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='PartWorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bom.partclassworkflowstate')),
                ('currently_assigned_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bom.part')),
                ('workflow', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bom.partclassworkflow')),
            ],
        ),
        migrations.AddConstraint(
            model_name='partclassworkflow',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_workflow_name_per_org'),
        ),
        migrations.AlterUniqueTogether(
            name='partclassworkflowstatetransition',
            unique_together={('source_state', 'target_state', 'workflow')},
        ),
    ]
